### ISSUE TITLE
Create Plceholder pages for, broken/invalid/under-development links.

### ISSUE THREAD

**Issue by Utkarsh1999** [avinashkranjan/Recess#113]
Create 2 placeholder pages for,
1. 404 Page not found: if URL is invalid, then show this to the user
2. Under-Development/Construction: If that page is under-development, then this should be shown to the user when a user tries to access that page.

**Comment by saikeshari** [comment]
I want to work on this. Please assign this to me.

**Comment by NehaK745** [comment]
Can you assign this issue to me?

**Comment by Jaagrav** [comment]
Could you assign this issue to me? I am already working on a new UI for the website, #96 which would simultaneously track this issue as well.

**Comment by Utkarsh1999** [comment]
@Jaagrav , issues need to be assigned on an FCFS basis, so I have to assign this to @NehaK745 . But you both can coordinate on this, right?

**Comment by Utkarsh1999** [comment]
I am assigning this to both of you, let me know if you have any problem with that.

**Comment by Jaagrav** [comment]
No no it's totally fine
