### ISSUE TITLE
Facebook Authentication Through Firebase

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Recess#117]
# AIM
- Facebook Authentication Through Firebase

# DETAILS
- Email Password authentication already added but not facebook authentication

**Comment by Jaagrav** [comment]
Can I work on this issue as well?

I will ping you the Google and Facebook auth buttons design on Discord

**Comment by avinashkranjan** [comment]
Sure Go Ahead @Jaagrav

**Comment by Utkarsh1999** [comment]
Hey @Jaagrav , any update on this?

**Comment by Ankita297** [comment]
Can i work on this @Utkarsh1999 @avinashkranjan ?

**Comment by Utkarsh1999** [comment]
> 
> 
> Can i work on this @Utkarsh1999 @avinashkranjan ?

yes you can, go ahead.
