### ISSUE TITLE
Google Authentication Through Firebase

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Recess#118]
# AIM
- Google Authentication Through Firebase

# DETAILS
- Email and Password authentication is already Present. Add Google Authentication

**Comment by Jaagrav** [comment]
Can I work on this issue?

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by avinashkranjan** [comment]
Sure Go Ahead @Jaagrav

**Comment by Jaagrav** [comment]
@avinashkranjan You can assign @Ankita297 as well btw, if you're ok with that.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @Ankita297

**Comment by Ankita297** [comment]
Sir i am not able to setup the project in my local repo ,Can you Please help me out .

**Comment by Ankita297** [comment]
Sir i am not able to setup the project in my local system  ,Can you Please help me out .

**Comment by Ankita297** [comment]
![MINGW64__f_Recess 20-03-2021 21_56_44](https://user-images.githubusercontent.com/67833077/111877124-c619aa00-89c7-11eb-9d7a-60db0644af16.png)

**Comment by Ankita297** [comment]
Sir i am not able to setup the project in my local repo ,Can you Please help me out .
@avinashkranjan @Jaagrav

**Comment by Jaagrav** [comment]
@Ankita297 You did not run `npm install`, did you?

**Comment by Ankita297** [comment]
I did .

**Comment by Ankita297** [comment]
I have followed the steps:
1.clone
2.npm install 
but after that it is giving me errors

**Comment by Ankita297** [comment]
![MINGW64__f_Recess 20-03-2021 22_56_14](https://user-images.githubusercontent.com/67833077/111880128-8787ed80-89cf-11eb-94e7-fba28082bda2.png)

**Comment by Ankita297** [comment]
i hav e also done npm clean cache

**Comment by Ankita297** [comment]
i have also done npm clean cache
 @Jaagrav

**Comment by Jaagrav** [comment]
Ok, try removing your package-lock || yarn.lock and remove node_modules
Use `rm -rf node_modules package-lock.json` 

And then re-install using `npm install`, let me know if it works then...

**Comment by Jaagrav** [comment]
I think it'd be better if we communicate over discord: jaagrav#4888

**Comment by Ankita297** [comment]
@avinashkranjan  have you enabled google auth ?
