### ISSUE TITLE
GitHub Action to Auto Deploy on Firebase 

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Recess#119]
# AIM
- GitHub Action to Auto Deploy on Firebase After Every Commit.

# DETAILS
- Currently It is done manually, 
- Add a `GH-Action` to automate the manual work

**Comment by itsIapetus** [comment]
I would like to work on this under gssoc, could you assign it to me?
Thanks!

**Comment by avinashkranjan** [comment]
Sure Go Ahead @itsIapetus
