### ISSUE TITLE
Add like dislike button on post

### ISSUE THREAD

**Issue by minukumari** [avinashkranjan/Recess#125]
Hey @avinashkranjan can we add like and dislike button on every post.

**Comment by hridhi** [comment]
Hey , i would like ot work on this issue. I am also a GSSoC participant so i would request you to add gssoc'21 tag thanks

**Comment by minukumari** [comment]
Hey I am also a GSSoC participant and i am waiting for approval. I would like to work on this.

**Comment by Utkarsh1999** [comment]
Go ahead, @minukumari.

**Comment by avinashkranjan** [comment]
Any Updated @minukumari

**Comment by Utkarsh1999** [comment]
Hey @minukumari , since you're not updating us on this so I am removing you from this issue.

**Comment by shobit1337** [comment]
@Utkarsh1999 Can I work on the like/dislike button feature? If yes please assign it to me 😃

**Comment by stuti-ui** [comment]
Hey, can I work on this issue?

**Comment by Utkarsh1999** [comment]
> 
> 
> @Utkarsh1999 Can I work on the like/dislike button feature? If yes please assign it to me 😃

Assigning to you, Go ahead!

**Comment by shobit1337** [comment]
#212 @avinashkranjan Please review the PR
