### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by hridhi** [avinashkranjan/Recess#127]
I thought of having a proper Main page for the website where there could be some description of the website, then links/buttons to direct to sign in/Signup pages and also with a preview. I am a GSSoC'21 participant and hopping you to add GSSoC tag thank you

**Comment by Jaagrav** [comment]
We are already working on it on another issue, you can check out the new design on this URL: https://recess-n3jc6ggz3-jaagrav.vercel.app/home
