### ISSUE TITLE
Twitter Sign in 

### ISSUE THREAD

**Issue by hridhi** [avinashkranjan/Recess#128]
Hey , i would like to work on twitter sign in/sign up  , i have worked on them before using react js and firebase hope you assign it to me and also add GSSoC tag Thanks !

**Comment by avinashkranjan** [comment]
Sure Go Ahead @hridhi

**Comment by Jaagrav** [comment]
Hey, can I work on this as well?

**Comment by Ankita297** [comment]
Can i work on this @avinashkranjan ?

**Comment by avinashkranjan** [comment]
If @Jaagrav Isn't interested, I can assign it you..as the issues are `FCFS`..

**Comment by Ankita297** [comment]
Okay @avinashkranjan

**Comment by Jaagrav** [comment]
Oh I'll make the PR soon @avinashkranjan

**Comment by Utkarsh1999** [comment]
@Jaagrav , any update on this?

**Comment by Jaagrav** [comment]
Sorry I am kinda busy with my exams, They'll be over by 30th so will work on Recess then... 😅

**Comment by Utkarsh1999** [comment]
> 
> 
> Sorry I am kinda busy with my exams, They'll be over by 30th so will work on Recess then... 😅
> The code is ready, I need just need to make the PR the same for Facebook sign-in #117

Hey @Jaagrav , Please do it at the earliest.

**Comment by Ankita297** [comment]
@Utkarsh1999 @avinashkranjan Can i work on this ?
