### ISSUE TITLE
New Color scheme to enhance the look

### ISSUE THREAD

**Issue by ManavArora26** [avinashkranjan/Recess#131]
**Is your feature request related to a problem? Please describe.**
No, I want to change the color scheme so as to make the website more appealing , youthful and fun

**Describe the solution you'd like**
i would change white color into some clean and energetic scheme so that it comes out more appealing to everyone

**Describe alternatives you've considered**
Some light shades of blue , orange and red mixed or seperately
**Additional context**
![1](https://user-images.githubusercontent.com/72567005/112046898-9a86f300-8b72-11eb-8ef6-2505fe68554a.PNG)
![2](https://user-images.githubusercontent.com/72567005/112046906-9c50b680-8b72-11eb-800d-f82770645bc4.PNG)
![3](https://user-images.githubusercontent.com/72567005/112046909-9e1a7a00-8b72-11eb-9023-2db29040f440.PNG)

**Comment by GurshehzadSingh** [comment]
im a gssoc participant and i would like to work on this issue

**Comment by Utkarsh1999** [comment]
@ManavArora26 , please mention a specific color you want to use for this. A screenshot with that color scheme would be great.

**Comment by Jaagrav** [comment]
@ManavArora26 Please create a proper Figma file before writing the code, this would help us visualize the new color scheme. Also there's a Material UI theme.js rule under `src/` that you can make changes to in order to change the color theme. Or else you'll break the dark mode and light mode switching.

**Comment by Utkarsh1999** [comment]
Hi @ManavArora26 , Since you're not responding to comments so I am closing this issue. Feel free to open another issue if you still want to work on this.
