### ISSUE TITLE
Persistence of User theme preference

### ISSUE THREAD

**Issue by aanchal-fatwani** [avinashkranjan/Recess#134]
**ISSUE DETAILS**
Currently, the user-selected theme preference (Dark / Light Mode) is not persisted and on reloading the application it resets to dark mode.
Visiting the application multiple times, the user would wish the application should handle and refer to the previously provided choice option from users.

**Comment by aanchal-fatwani** [comment]
Hey @avinashkranjan, @Utkarsh1999, @abhishek2x, I am a GSSOC 2021 participant. I would like to work on the issue. 
Could you please update the issue with relevant tags and assign the same?

**Comment by abhishek2x** [comment]
Sure, go ahead.

**Comment by shaswata1029** [comment]
Hey @avinashkranjan, @Utkarsh1999, @abhishek2x, I am a GSSOC 2021 participant. I would like to work on the issue.As the issue has not been resolved I would like to work in this issue Can u assign it to me also
