### ISSUE TITLE
[GSSoC' 21] Correct Upload route

### ISSUE THREAD

**Issue by sakshi-s** [avinashkranjan/Recess#140]
The Upload icon on the sidebar currently redirects to homepage as follows:
![before1](https://user-images.githubusercontent.com/39264146/112589885-e1514300-8e27-11eb-9735-1e8a242dd86e.PNG)

I will make it redirect to upload form as follows:
![after1](https://user-images.githubusercontent.com/39264146/112589972-0fcf1e00-8e28-11eb-9417-aaf5a8bb0b8a.PNG)

**Comment by Utkarsh1999** [comment]
Hi @sakshi-s , this has been implemented by another contributor. He fixed this in his PR.
