### ISSUE TITLE
Add github action to auto label issues

### ISSUE THREAD

**Issue by muthuannamalai12** [avinashkranjan/Recess#141]
Add GitHub action to auto label issues with gssoc21 label when contributor asks to work under gssoc21.

**Comment by GurshehzadSingh** [comment]
im a gssoc participant and i would like to work on this issue

**Comment by abhishek2x** [comment]
@GurshehzadSingh, go ahead.

**Comment by muthuannamalai12** [comment]
@abhishek2x Can you assign me as  I have created the issue I am also a participant of Girl Script Summer of Code

**Comment by abhishek2x** [comment]
Since you create the issue and you want to work on it, go ahead @muthuannamalai12
