### ISSUE TITLE
Logo is not clickable

### ISSUE THREAD

**Issue by aanchal-fatwani** [avinashkranjan/Recess#143]
ISSUE DETAILS
Currently, the logo of the application is not clickable. 
The user expects the logo to be clickable and should redirect to the home page of the application as a standard practice.

**Comment by aanchal-fatwani** [comment]
Hey @avinashkranjan, @Utkarsh1999, @abhishek2x, I am a GSSOC 2021 participant. I would like to work on the issue. 
Could you please update the issue with relevant tags and assign the same?

**Comment by abhishek2x** [comment]
Sure @aanchal-fatwani, go ahead.

**Comment by shaswata1029** [comment]
Hey @avinashkranjan, @Utkarsh1999, @abhishek2x, I am a GSSOC 2021 participant. I would like to work on the issue. I have already tested it on my localhost and I would like to contribute to this
