### ISSUE TITLE
Single Page Application

### ISSUE THREAD

**Issue by shaswata1029** [avinashkranjan/Recess#145]
Currently on clicking the links the page refreshes and the application needs to fetch all the details again from the server. It would be good if this is to be converted into a single page application

**Comment by shaswata1029** [comment]
Hey @avinashkranjan, @Utkarsh1999, @abhishek2x, I am a GSSOC 2021 participant. I would like to work on the issue.
Could you please update the issue with relevant tags and assign the same?

**Comment by Utkarsh1999** [comment]
Hey @shaswata1029 , This is already been implemented by another PR.
