### ISSUE TITLE
Modal and Comment Hiding 

### ISSUE THREAD

**Issue by Inventor77** [avinashkranjan/Recess#146]
**Is your feature request related to a problem? Please describe.**
Many Comments on Post makes it bit Messy and the Height of Post on Main wall Changes depending on Number of comments makes all the post uneven 

**Describe the solution you'd like**
-> Fixing the Height of post and hiding the comments
-> Able to View few comments on clicking button "View Comment" 
-> Able to view all comment by clicking on "more" button which makes appearance of  Modal 
-> On Modal, Post image will be on left side and all the comment on right side makes to view all the comments by scrolling

**Additional context**
Can Mentors overlook on this and feels worth changing Please assign me this issue and labeling it with gssoc21

![Screenshot (575)](https://user-images.githubusercontent.com/62959484/112748584-3e8cf600-8fda-11eb-9ca2-82d69401a8a8.png)

**Comment by Inventor77** [comment]
@avinashkranjan Please Mentor Assign me this Issue ,I have already worked on it and have a completed code. I will PR for it as soon as it will be assigned to me

**Comment by Utkarsh1999** [comment]
Hi @Inventor77 , i have assigned this issue to you, also your Is approved and will be merged in some time.

**Comment by Inventor77** [comment]
> Hi @Inventor77 , i have assigned this issue to you, also your PR is approved and will be merged in some time.

Sir I Made two branches so This PR is not the whole work it will Only hide the Comments I have to do Another OR for Modal now. I was not familiar with this thing that I can't PR two Branches

**Comment by Inventor77** [comment]
@avinashkranjan Thanks Sir for Merging the PR
