### ISSUE TITLE
Adding a 404 page

### ISSUE THREAD

**Issue by ShambhaviSharma0110** [avinashkranjan/Recess#148]
**Is your feature request related to a problem? Please describe.**
For all the unknown routes that can be looked for I would like to make a 404 page as this is the most neglected page
**Describe the solution you'd like**
For any unknown route this page would show up

**Describe alternatives you've considered**
I'll add a 404 page that's it
**Additional context**
NA

**Comment by avinashkranjan** [comment]
Hey @ShambhaviSharma0110 This feature has already been worked on and done..in #113
