### ISSUE TITLE
Avatar icon overlaps foreground layer

### ISSUE THREAD

**Issue by aanchal-fatwani** [avinashkranjan/Recess#152]
ISSUE DETAILS
Currently, on responsive view, the avatar icon overlaps the foreground layer and shows above the Sidebar area.
This hampers user experience and visibility of the sidebar navigation options. 

![Z-indexIssue](https://user-images.githubusercontent.com/63228776/113160013-b6695380-925a-11eb-9243-4347285d170c.png)

**Comment by aanchal-fatwani** [comment]
Hey @avinashkranjan, @Utkarsh1999, @abhishek2x, I am a GSSOC 2021 participant. I would like to work on the issue. 
Could you please update the issue with relevant tags and assign the same?

**Comment by Utkarsh1999** [comment]
Hi @aanchal-fatwani , UI is updated recently, can you confirm if this issue still exists or not?

**Comment by aanchal-fatwani** [comment]
@Utkarsh1999, the issue seems to have been resolved with recently introduced UI changes. It is not occurring anymore.

**Comment by avinashkranjan** [comment]
Okay @aanchal-fatwani then closing this Issue
