### ISSUE TITLE
You need to login to post, can be done as a toast message.

### ISSUE THREAD

**Issue by akshay1027** [avinashkranjan/Recess#157]
**Is your feature request related to a problem? Please describe.**
You need to login to post, can be done as a toast message so that its easier for the user.

**Comment by Utkarsh1999** [comment]
hey @akshay1027 , describe a little more on what exactly you want to do in this issue.

**Comment by akshay1027** [comment]
After the user clicks the url and enters the website, we can do like a pop up or toast message stated that they have to "log in/sign up to post and comment" 

somewhere here we can do this @Utkarsh1999 

![2021-04-07 (3)_LI](https://user-images.githubusercontent.com/65683151/113892563-c09fca80-97e3-11eb-8446-b5974bcf6777.jpg)

**Comment by akshay1027** [comment]
On this website just click the submit button without entering anything! you will see a pop up message @Utkarsh1999 

https://akshayrr-memestream.vercel.app/

**Comment by avinashkranjan** [comment]
Sure Go Ahead @akshay1027
