### ISSUE TITLE
ERR in documentation in contributing.md

### ISSUE THREAD

**Issue by ArchishmanSengupta** [avinashkranjan/Recess#162]
Error link : [click](https://github.com/avinashkranjan/Recess/blob/master/CONTRIBUTING.md)
```
CONTRIBUTING.MD 

Step 2 : Fork the Project. Fork this Repository.
 This will create a Local Copy of this Repository on your Github Profile. 
Keep a reference to the original project in upstream remote.

$ git clone https://github.com/<your-username>/Recess
$ cd Recess
$ git remote add upstream https://github.com/avinashkranjan/Recess
```

The above codes restricts us to function git commands. The proper way is:

```
$ git clone https://github.com/<your-username>/Recess.git
$ cd Recess
$ git remote add upstream https://github.com/avinashkranjan/Recess.git

```

i can make the necessary changes. Please add GSSoC label and assign me this task

**Comment by ArchishmanSengupta** [comment]
@avinashkranjan please assign me this task

**Comment by avinashkranjan** [comment]
Hey @ArchishmanSengupta I know you guys are beginners but it would be of any significance as it would awarded with no marks..So, Kindly, Work on Something which helps in learning and growing.

**Comment by ArchishmanSengupta** [comment]
> Hey @ArchishmanSengupta I know you guys are beginners but it would be of any significance as it would awarded with no marks..So, Kindly, Work on Something which helps in learning and growing. 

Okay
