### ISSUE TITLE
SplashScreenAddition 

### ISSUE THREAD

**Issue by AakankshaKamal** [avinashkranjan/Recess#164]
A splash screen at the beginning just before opening the website,that would look better.

**Comment by avinashkranjan** [comment]
Sure Go Ahead @AakankshaKamal

**Comment by AakankshaKamal** [comment]
Thank You .

**Comment by AakankshaKamal** [comment]
https://user-images.githubusercontent.com/58944717/115048737-85924b00-9ef7-11eb-9fee-924f49d6f213.mp4
Please do have a look at the design and give your views.Thank You.

**Comment by Utkarsh1999** [comment]
Could you change the text, "Wait a moment, while we launch the website"? to something more creative :p 
Also, the font is different, please change that too.

> 
> 
> https://user-images.githubusercontent.com/58944717/115048737-85924b00-9ef7-11eb-9fee-924f49d6f213.mp4
> Please do have a look at the design and give your views.Thank You.

**Comment by AakankshaKamal** [comment]
Ok I ll make the changes

**Comment by Utkarsh1999** [comment]
> 
> 
> Ok I ll make the changes
> How about : "A New World is loading .Think, Explore and Meet "

yes this one is better.

**Comment by AakankshaKamal** [comment]
![Screenshot 2021-04-25 170223](https://user-images.githubusercontent.com/58944717/115991865-21067880-a5e8-11eb-9a2c-394a01f450a1.png)
 Please do have a look at it.

**Comment by Utkarsh1999** [comment]
> 
> 
> ![Screenshot 2021-04-25 170223](https://user-images.githubusercontent.com/58944717/115991865-21067880-a5e8-11eb-9a2c-394a01f450a1.png)
> Please do have a look at it.

Please change the font to default of project, rest if good.

**Comment by AakankshaKamal** [comment]
I have made PR with the changes.Please do have a look upon it
