### ISSUE TITLE
Svg Morphing Animation

### ISSUE THREAD

**Issue by Inventor77** [avinashkranjan/Recess#166]
**Is your feature request related to a problem? Please describe.**
This feature is not related to any problem , just an enhancement to UI of theme toggling SVG

**Describe the solution you'd like**
A clear and subtle SVG Morphing Animation

**Additional context**
@AnjaliSrivastava722  @Sristi27 @Utkarsh1999  Can Mentors overlook on this and feels worth changing Please assign me this issue and labeling it with gssoc21

![Svg Morphing Animation](https://user-images.githubusercontent.com/62959484/114589629-7a47e100-9ca5-11eb-81a4-54e8d5a44351.gif)

**Comment by Inventor77** [comment]
@avinashkranjan Sir please Assign me this Issue and give it a level you like

**Comment by Utkarsh1999** [comment]
Hi @Inventor77 , Go ahead with this.

**Comment by Inventor77** [comment]
@Utkarsh1999 Thanks alot sir
