### ISSUE TITLE
Add github-actions to greet everytime a pr is merged successfully

### ISSUE THREAD

**Issue by AB-san** [avinashkranjan/Recess#172]
**Is your feature request related to a problem? Please describe.**
No such problem

**Describe the solution you'd like**
I would like to add github-actions to send greetings to all the new contributors who are contributing to this project for the first time.
Resource that i would like to use -
actions/first-interaction@v1

**Comment by Utkarsh1999** [comment]
Go ahead @AB-san

**Comment by Utkarsh1999** [comment]
Okay, I changed the issue title. go ahead with this

**Comment by AB-san** [comment]
> Okay, I changed the issue title. go ahead with this

Okay ,sure
