### ISSUE TITLE
Add a welcome bot 

### ISSUE THREAD

**Issue by Ankita297** [avinashkranjan/Recess#177]
**Is your feature request related to a problem? Please describe.**
github action to add  a message to greet when contributor makes his/her first PR and first issue .
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ankita297** [comment]
@avinashkranjan can i work on this ?

**Comment by Ankita297** [comment]
![New issue · Issue #1 · Ankita297_Story - Google Chrome 22-04-2021 00_53_11](https://user-images.githubusercontent.com/67833077/115944577-368a7e00-a4d4-11eb-9774-51d4ced4a076.png)

**Comment by avinashkranjan** [comment]
Sure Go Ahead @Ankita297
