### ISSUE TITLE
About us page! Feature request!!

### ISSUE THREAD

**Issue by akshay1027** [avinashkranjan/Recess#185]
**Is your feature request related to a problem? Please describe.**
About us page with the following:
1) - [x] about us new project setup, simple layout, content
2) - [ ]  Footer for this 
3) - [ ]  contact us form
4) - [ ]  backend for the same 
5) - [ ]  showcasing contributors in about us page 
6) - [ ]  FAQ page
7) - [x] About us Link in navbar

**Comment by akshay1027** [comment]
I would love to work on them all and make these improvements @avinashkranjan @Utkarsh1999

**Comment by avinashkranjan** [comment]
Sure Go Ahead @akshay1027 , Follow the Color and font theme of the project..

**Comment by akshay1027** [comment]
Sure, Thanks! As you can see I have broken down the whole page into different parts! I will make PRs in the same way as every part is a level 3 issue in itself

**Comment by akshay1027** [comment]
After finishing a part, I will make the PR and check the corresponding boxes, so that you can see the progress and Give the levels as well

**Comment by akshay1027** [comment]
@Utkarsh1999 @avinashkranjan can you please add labels and merge the PRs i have made till now, so that I can get points! Please give me assurance, points is important for me right now! i hope you can understand my situation! Thank you!

**Comment by akshay1027** [comment]
If this is merged, i will make more PRs, please reply!

**Comment by avinashkranjan** [comment]
Hey @akshay1027 All the PRs which are a part of GSSOC'21 would get merged..Don't worry about that..you'll get your score..
