### ISSUE TITLE
Github Authentication 

### ISSUE THREAD

**Issue by Ankita297** [avinashkranjan/Recess#201]
**Is your feature request related to a problem? Please describe.**
Authentication through github 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ankita297** [comment]
Can i work on this @avinashkranjan @Utkarsh1999 ?

**Comment by Utkarsh1999** [comment]
@Ankita297 , go ahead. assigning to you!

**Comment by Ankita297** [comment]
@Utkarsh1999 Sir have you enabled github auth ?

**Comment by Utkarsh1999** [comment]
> 
> 
> @Utkarsh1999 Sir have you enabled GitHub auth?

I don't have the access, @avinashkranjan please do the needful
