### ISSUE TITLE
[BUG] All Posts are loading twice

### ISSUE THREAD

**Issue by shobit1337** [avinashkranjan/Recess#216]
**Describe the bug**
All the posts are rendering twice on the Homepage

**Expected behavior**
The posts should load only once.

**Video**
https://www.loom.com/share/0a87616bd05046e9bdec70d57698334f

**Additional context**
I will fix this issue by looking into the reason that is causing this, Kindly assign it to me.

**Comment by avinashkranjan** [comment]
Go Ahead @shobit1337
