### ISSUE TITLE
Hide the comment box if a user is not signed in.

### ISSUE THREAD

**Issue by AsavariA** [avinashkranjan/Recess#255]
**Describe the bug**
Hiding the comment box if a **user is not signed** in provides for a better UX. It's not a good idea to have features users cannot access.

**Current behavior**
Unresponsive comment box, which doesn't do anything on commenting.
![image](https://user-images.githubusercontent.com/77312781/129045124-252030b7-59b1-4a4a-9681-107cbf205ec5.png)

**Expected behavior**
Maybe like a message in place of the text field saying "Sign in to leave a comment!"

**Comment by avinashkranjan** [comment]
Thank You For Feedback...would you like to work on it @AsavariA

**Comment by AsavariA** [comment]
Sure @avinashkranjan , assign it to me.

**Comment by avinashkranjan** [comment]
Great..Go Ahead @AsavariA

**Comment by AsavariA** [comment]
@avinashkranjan please review the PR
