### ISSUE TITLE
Improve the UI of upload section with some extra features

### ISSUE THREAD

**Issue by bitaashna** [avinashkranjan/Recess#50]
I would like to work on this issue as a part of GSSOC'21.
can u please assign it to me.

**Comment by ShivamTyagi12345** [comment]
This project, from GSSOC21, interests me, and i would like to add  few additional features
1).Like counters
2).double tap to like features.

plz assign if possible
![Screenshot (141)](https://user-images.githubusercontent.com/60812924/110441805-2cf1b600-80e0-11eb-97a9-c3f79543673d.png)

**Comment by avinashkranjan** [comment]
Kindly Describe the Features Mentioned @bitaashna 
Hey @Sakshi0401 Issues are First Come First Serve..

**Comment by bitaashna** [comment]
@avinashkranjan 
Features like adding Gifs,images or videos.
Giving a stylish touch to that upload container.
Improving the UI of the box.

**Comment by avinashkranjan** [comment]
Go Ahead then @bitaashna Looking forward to your implementation

**Comment by bitaashna** [comment]
Hey @avinashkranjan ! I have given stylish touch to upload section but till now images or video or gif can be uploaded but when we click on upload and the post is generated , there we are not getting any video or gif if they are uploaded. I think I will be needing firebase authentication so that this can be uploaded to database (to update settings in database to upload video or gif).
PLease look into it once.

**Comment by bitaashna** [comment]
I have styled the upload section till now. working with how to add videos and gifs
![Recess - Students Social Media - Google Chrome 13-03-2021 18_39_22 (2)](https://user-images.githubusercontent.com/57864526/111041858-fc6f8c00-83ff-11eb-9c25-f24cce3301a3.png)

**Comment by Jaagrav** [comment]
I have designed and created the new upload page, please can you assign me as well?

![Desktop](https://user-images.githubusercontent.com/52719271/111707355-e7648400-8869-11eb-8816-fcdd60ccf533.png)
![Mobile](https://user-images.githubusercontent.com/52719271/111707393-f8ad9080-8869-11eb-85cf-6ec6e1169500.png)

There's a built-in loader as well which is shown when the user clicks on upload.

You can check it out working live here: https://recess-n3jc6ggz3-jaagrav.vercel.app/

**Comment by bitaashna** [comment]
@avinashkranjan Please look ito the PR created by @Jaagrav . Now I can start working on it to add videos and gifs.

**Comment by Inventor77** [comment]
Hello Mentors Since No one is Assigned to this project please Assign it to me I have some Ideas to Implement here
