### ISSUE TITLE
add functionalities of double tap like and Responses

### ISSUE THREAD

**Issue by ShivamTyagi12345** [avinashkranjan/Recess#51]
hello,
this project from gssoc21,intrests me .I would like to add few additional functions for a better interaction:
1).Double tap to like
2).emoji response and counter

Plz assign if possible.
Heres a preview attached.
![Screenshot (141)](https://user-images.githubusercontent.com/60812924/110442739-2152bf00-80e1-11eb-9377-d3015d1f7759.png)

**Comment by avinashkranjan** [comment]
Assigned to you @ShivamTyagi12345

**Comment by ShivamTyagi12345** [comment]
hello @mentor

I came across numerous snippets of code for the "double-tap-to -like feature", but none of them are helpful enough.

may i plz get some help here.thanks
