### ISSUE TITLE
Add comment functionality

### ISSUE THREAD

**Issue by kokilgupta** [avinashkranjan/Recess#52]
I would like to add a comment button and upon clicking that button we can view all the comments.

**Comment by kokilgupta** [comment]
Can I work on this issue?
If possible please assign it to me

**Comment by avinashkranjan** [comment]
Assigned to you @kokilgupta

**Comment by nitinNT** [comment]
@avinashkranjan this I already fixed. Please Check the PR request

**Comment by kokilgupta** [comment]
I have made a PR for this issue. Please review and merge it
