### ISSUE TITLE
[GSSOC'21] Add side navigation bar using React JS. 

### ISSUE THREAD

**Issue by Sakshi0401** [avinashkranjan/Recess#53]
![image](https://user-images.githubusercontent.com/64726139/110457001-31be6600-80f0-11eb-8051-767433dd45a5.png)

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by avinashkranjan** [comment]
Assigned to you @Sakshi0401 Keep the Content of the Navbar Vertically middle

**Comment by Sakshi0401** [comment]
Hey @avinashkranjan  I have made all necessary changes. Attaching picture for reference : 
![image](https://user-images.githubusercontent.com/64726139/110595865-9a671a80-81a4-11eb-9c16-28a8abeae40f.png)
Let me know if there are any changes.
