### ISSUE TITLE
[GSSoC'21] Add an Universal Navigation bar with sidebar of the user.

### ISSUE THREAD

**Issue by ArchishmanSengupta** [avinashkranjan/Recess#55]
I propose to add an Universal Navigation bar with Search + Home + messages +notifications with sidebar where the person who signs in can view his/her profile.

need your permission & kindly Add a label of GSSoC'21 so that i can work on this asap

**Comment by avinashkranjan** [comment]
Hey @ArchishmanSengupta Kindly refer [here](https://github.com/avinashkranjan/Recess/issues/53) /#53 You and @Sakshi0401 can work on this together.. Assigned to you @ArchishmanSengupta

**Comment by ArchishmanSengupta** [comment]
```
Failed to compile.

./src/index.js 1:37
Module parse failed: Unexpected token (1:37)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> $RefreshRuntime$ = require('F:/GSSoC'21/Recess/node_modules/react-refresh/runtime.js');
| $RefreshSetup$(module.id);
|
```
getting error when doing npm start

**Comment by avinashkranjan** [comment]
> ```
> Failed to compile.
> 
> ./src/index.js 1:37
> Module parse failed: Unexpected token (1:37)
> File was processed with these loaders:
>  * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
>  * ./node_modules/babel-loader/lib/index.js
> You may need an additional loader to handle the result of these loaders.
> > $RefreshRuntime$ = require('F:/GSSoC'21/Recess/node_modules/react-refresh/runtime.js');
> | $RefreshSetup$(module.id);
> |
> ```
> 
> getting error when doing npm start

There's some issue with your npm..It works fine in my system 
![Screenshot 2021-03-10 020026](https://user-images.githubusercontent.com/55796944/110533920-7e339100-8144-11eb-9845-6cb977f31889.png)

**Comment by ArchishmanSengupta** [comment]
> > ```
> > Failed to compile.
> > 
> > ./src/index.js 1:37
> > Module parse failed: Unexpected token (1:37)
> > File was processed with these loaders:
> >  * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
> >  * ./node_modules/babel-loader/lib/index.js
> > You may need an additional loader to handle the result of these loaders.
> > > $RefreshRuntime$ = require('F:/GSSoC'21/Recess/node_modules/react-refresh/runtime.js');
> > | $RefreshSetup$(module.id);
> > |
> > ```
> > 
> > getting error when doing npm start
> 
> There's some issue with your npm..It works fine in my system 
> ![Screenshot 2021-03-10 020026](https://user-images.githubusercontent.com/55796944/110533920-7e339100-8144-11eb-9845-6cb977f31889.png)
> 

Yes now it is working, my node was not of the lastest version.
