### ISSUE TITLE
[GSSoC'21] feature: Adding profile page 

### ISSUE THREAD

**Issue by Aniket1103** [avinashkranjan/Recess#57]
We need to create a profile page, where we can view the following: 

- personal details like name, user id, bio, etc
- number of followers & followings
- posts, saved posts, etc

If the user is viewing others profile he/she will be getting the option to follow/unfollow
whereas id he/she is viewing his/her own profile he will be getting the option to edit profile

The following image could be the basic structure for the profile page
![Screenshot (73)](https://user-images.githubusercontent.com/55594740/110501672-6ba76080-8120-11eb-9089-2eeb4f20adfa.png)

Please suggest any more options that could be added (if any).

**Comment by avinashkranjan** [comment]
Assigned to you @Aniket1103

**Comment by Aniket1103** [comment]
@avinashkranjan In this project react-router part is not yet being implemented.
Should I implement it so that I will be able to link the profile page to it?

**Comment by avinashkranjan** [comment]
Yes @Aniket1103

**Comment by Aniket1103** [comment]
Ok, Thanks @avinashkranjan,
currently, I managed to implement routing and linking in the app but will definitely consider contacting through Discord if I require any help.
Thank you.

**Comment by Jaagrav** [comment]
Since we have not yet worked on a definite follower system, I have designed something that could work in the meanwhile and look fine as well, @avinashkranjan check this out.

![Profile](https://user-images.githubusercontent.com/52719271/111709215-3c55c980-886d-11eb-9600-ac759bd2dd05.png)
