### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by soha28** [avinashkranjan/Recess#64]
I want to work on this issue under GSSOC'21. Can u please assign this to me ?

**Comment by avinashkranjan** [comment]
Go Ahead @soha28

**Comment by avinashkranjan** [comment]
Two can Participate You can help @soha28 out and Inform me about the contributions. So, I can give points to you guys

**Comment by Priyanka7011** [comment]
@avinashkranjan can I work with @soha28 and @Jaagrav on this issue ??
please let me now if I can .

Thank You

**Comment by avinashkranjan** [comment]
Hey @Priyanka7011 You can ask these guys @soha28 and @Jaagrav If they need any help..If not Look for other open issues..

**Comment by Priyanka7011** [comment]
Okay 
Thank You

**Comment by Jaagrav** [comment]
I see quite a lot of people interested in the same issues, now if I have permission from GSSoC mentor, I'd like the contributors to join this [WhatsApp group](https://chat.whatsapp.com/Cq1OZiXX4V9KmRkvOp3w8s) in order to be able to analyze the issues related to this project more decisively.

**Comment by avinashkranjan** [comment]
Hey @Jaagrav Participants would be given access to Project Channel Tonight. Don't worry about it.

**Comment by Jaagrav** [comment]
@avinashkranjan I have created #92 to track this issue, please check it out, and let me know the changes you'd like to be made.

**Comment by Jaagrav** [comment]
Since we agreed to work on a completely new UI, this issue would automatically be resolved once #88 is resolved.
