### ISSUE TITLE
Changing UI of Upload Form

### ISSUE THREAD

**Issue by Sristi27** [avinashkranjan/Recess#69]
I would like to work on inproving the UI of uploading a new user experience.Could you please assign the issue to me?
![Screenshot 2021-03-10 at 5 48 37 PM](https://user-images.githubusercontent.com/53037053/110628507-183d1d00-81c9-11eb-9c6c-1e63e3b14944.png)

**Comment by ankita-04** [comment]
@avinashkranjan  Please assign this issue to me. I am a GSSOC'21 participant.

**Comment by Ankita297** [comment]
@avinashkranjan Can i work on this ?

**Comment by Jaagrav** [comment]
I think this is issue is already being tracked with #50. Anyway I'd like to work on this as a part of our new UI design...

![Desktop](https://user-images.githubusercontent.com/52719271/111709598-e6cdec80-886d-11eb-85a6-c14c0c182ea0.png)
![Mobile](https://user-images.githubusercontent.com/52719271/111709603-eb92a080-886d-11eb-801b-e1255acff336.png)

**Comment by Sristi27** [comment]
I have already created the PR and got it approved . Do check it out @avinashkranjan .
THANKS for the great opportunity and learning experience!
