### ISSUE TITLE
Improving the Navigation Bar

### ISSUE THREAD

**Issue by AnjaliSrivastava722** [avinashkranjan/Recess#77]
The navigation bar has No spacing between the 2 buttons. Also the text on these Buttons should be LOGIN and Sign Up .

**Describe the solution you'd like**
I would like to bring about spacing between the buttons and also change the text to LOGIN and SIGN UP.
<img width="576" alt="nav" src="https://user-images.githubusercontent.com/43489841/110686898-f01fdf00-8205-11eb-853c-c8b8b013f003.png">

I would like to add these features as GSSOC participant.

**Comment by Priyanka7011** [comment]
hii I am a GSSOC 2021 participant.
 I would love to work on this issue.
Please assign me this.
Thank You

**Comment by tanyalava** [comment]
HI! I am a  GSSOC 2021 participant and would really like to work on this issue. I can definitely make the navigation bar look better and can add new features to it and make it more attractive.

**Comment by Utkarsh1999** [comment]
@AnjaliSrivastava722  I assigned this issue to you. Go ahead and make the changes you suggested.

**Comment by AnjaliSrivastava722** [comment]
Thank You !
