### ISSUE TITLE
Alignment of the posts 

### ISSUE THREAD

**Issue by Priyanka7011** [avinashkranjan/Recess#80]
Hii ! I am a GSSOC 2021 participant.
I think Alignment of posts in desktop mode can be changed. It should be aligned horizontally like 3 posts in one row and then we can increase the columns as needed. In mobile mode It should be aligned column wise which is already there.

please assign me this issue .I can fix it . 
Thank You

**Comment by Utkarsh1999** [comment]
Hi @Priyanka7011  , let's keep them in the way as they are.
