### ISSUE TITLE
Add Footer in the website

### ISSUE THREAD

**Issue by lavanya243** [avinashkranjan/Recess#87]
Hey @avinashkranjan  , I am Lavanya Narayanan, a GSSOC, 2021 participant.
I want to work on the footer issue.

I would like to request you to kindly assign me this problem.

**Comment by Aman1905** [comment]
Hey @avinashkranjan This is Aman Chopra , a GSSOC 21 participant I would also like to work on the footer of the project using reactjs. I would request you to kindly assign me this

Thank You

**Comment by Utkarsh1999** [comment]
@lavanya243  I am assigning this issue to you, go ahead and start working on this.

**Comment by lavanya243** [comment]
> @lavanya243 I am assigning this issue to you, go ahead and start working on this.

Okay. Thank you!
