### ISSUE TITLE
Improve UI using Material UI

### ISSUE THREAD

**Issue by lavanya243** [avinashkranjan/Recess#88]
Hey @avinashkranjan , I am Lavanya Narayanan, a GSSOC, 2021 participant.
I want to improve the UI using Material UI.

I would like to request you to kindly assign me this problem.

**Comment by Aman1905** [comment]
Hey @avinashkranjan This is Aman Chopra , a GSSOC 21 participant I would also like to work on the UI of the project using material UI . I would request you to kindly assign me this 

Thank You

**Comment by abhishek2x** [comment]
Assigning this issue to @lavanya243. Move ahead with the same.

**Comment by lavanya243** [comment]
Okay @abhishek2x , thank you!

**Comment by lavanya243** [comment]
> Assigning this issue to @lavanya243. Move ahead with the same.

Okay @abhishek2x  thank you!

**Comment by Jaagrav** [comment]
I am working on this issue already, can you please assign me before it goes stale?
