### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [avinashkranjan/Recess#91]
Hey ! I would like to add the folllowing in contributing.md

1. Update your local and forked repo as the changes are made in the upstream
2. Squashing the commits
I would like to do this under GSSOC'21

**Comment by Pranjal-2001** [comment]
could you please assign it to me?

**Comment by khareyash05** [comment]
@Pranjal-2001  Sorry but I am already working on this

**Comment by Utkarsh1999** [comment]
Hey @Pranjal-2001 , we are assigning issues on FCFS basis, so I can't assign this one to you.

@khareyash05 , a word of advice, never start working on any issue if it not assigned to you.

**Comment by khareyash05** [comment]
@Utkarsh1999 I am sorry but the labels were added to my issue and that i think means that the person wants me to start doing

**Comment by khareyash05** [comment]
@Utkarsh1999 I will remember this from now on thanx
