### ISSUE TITLE
We can change the "Login" in the home page

### ISSUE THREAD

**Issue by Suvojit-roy** [avinashkranjan/Recess#95]
Though the project has the login option at the bottom of the page the login word can be a link 

This link will lead the user to the login page. This will increase the user experience

![Screenshot (4)](https://user-images.githubusercontent.com/56533500/111032556-d57e7d80-8432-11eb-9f27-d912273edee6.png)

I would like to work on this issue and solve it. I am a a participant of GSSOC .Please do assign me to do this.

**Comment by abhishek2x** [comment]
Assigning to @Suvojit-roy. 
Consider having a modal kind of component, instead of a separate page, that pops up on the login button is clicked.

To ahead with this.

**Comment by Suvojit-roy** [comment]
I am on it

**Comment by Suvojit-roy** [comment]
Hey @abhishek2x  do check it. I have done the PR
