### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by Suvojit-roy** [avinashkranjan/Recess#96]
The UI is simple and the color combinations are not soothing to the eye.

I would like to change the color combination to a single color. For example: Shades of blue and a different shade for some other important options. This will maintain the uniformity of the project.

I have worked on same type of projects making clones of website. Please do assign me this one. I am a participant of GSSOC'21.

**Comment by Jaagrav** [comment]
Somebody assign me to this issue, I have a [figma design](https://www.figma.com/file/XiKOkC7X2SHIIhggRyqePW/Recess?node-id=0%3A1) ready to tackle and therefore I'd also like to work on it. Here are the images of the UI that I designed, @Suvojit-roy let me know if you want to make any changes to the UI since I am starting to work on it.

**Comment by Suvojit-roy** [comment]
Yeah i think that you should go for some other color combination.This is a high contrast design that makes it look funky rather than something official.

**Comment by Jaagrav** [comment]
Yeah but if you consider Twitter's or Instagram's dark theme, keeping a color palette, in contrast, makes it even more attractive. I tried to follow their design rules because firstly they were not only simple and minimal but also easy to eyes even with the contrast. What do you think?

**Comment by Suvojit-roy** [comment]
Yeah everything looks good just changing the neon shade a little will help it

**Comment by Jaagrav** [comment]
Can you make the changes you'd like? Check your email I have sent you an invite from figma.

**Comment by Suvojit-roy** [comment]
I didnt receive the mail .Please do resend me again or send it here.

**Comment by Jaagrav** [comment]
This issue should close #64

**Comment by Suvojit-roy** [comment]
hey @Jaagrav  you can send me that link and we can work on this together

**Comment by Jaagrav** [comment]
The new UI is available at: https://recess-n3jc6ggz3-jaagrav.vercel.app/home 

Still working on it... If you can, please design the 404 and under dev pages,
Thank you.

**Comment by avinashkranjan** [comment]
Loved the Implementation @Jaagrav
